[package]
name = "nochat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
pubsub = "*"
urlencoding = "2.1.0"
ammonia = "3"
